---
- name: Keybindings for move window to workspace
  ansible.builtin.command: "gsettings set org.cinnamon.desktop.keybindings.wm {{ item }}"
  with_items:
    - move-to-workspace-1 "['<Primary><Super>1']"
    - move-to-workspace-2 "['<Primary><Super>2']"
    - move-to-workspace-3 "['<Primary><Super>3']"
    - move-to-workspace-4 "['<Primary><Super>4']"

- name: Keybindings for switch to workspace
  ansible.builtin.command: "gsettings set org.cinnamon.desktop.keybindings.wm {{ item }}"
  with_items:
    - switch-to-workspace-1 "['<Primary>1']"
    - switch-to-workspace-2 "['<Primary>2']"
    - switch-to-workspace-3 "['<Primary>3']"
    - switch-to-workspace-4 "['<Primary>4']"

- name: Keybindings for toggle fullscreen
  ansible.builtin.command: "gsettings set org.cinnamon.desktop.keybindings.wm {{ item }}"
  with_items:
    - toggle-fullscreen "['<Super>f']"

- name: Keybindings for launching terminal
  ansible.builtin.command: "gsettings set org.cinnamon.desktop.keybindings.media-keys {{ item }}"
  with_items:
    - terminal "['<Primary><Alt>t', '<Primary>grave', '<Super>Return']"
